### ISSUE TITLE
Move arcticdata.io (Production) to Kubernetes

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1954]
Similar to #1932; 

## checklist:

- [x] Work with @nickatnceas to copy production data for testing: 
    - [x] Time how long it takes to...
        - [x] Copy the production postgres data (`arcticdata.io:/var/lib/postgresql`) to the PROD ceph volume at `/mnt/ceph/repos/arctic/postgresql` (treat it like a hot backup).
            - NOTE: we do not need the `/var/lib/postgresql/10` directory
        - [x] copy the following subset of production data from `arcticdata.io:/var/metacat` to the PROD ceph volume at `/mnt/ceph/repos/arctic/metacat`:

            ```shell
            # /var/metacat/...
            16K	    ./certs
            63T	    ./data
            8.0K        ./dataone
            3.9G        ./documents
            0           ./inline-data
            500K        ./logs
            ``` 
            - Actual Times taken for /var/metacat/data:
              - initial rsync
                ```shell
                root@arctica:/var/metacat# time rsync -aHAX --delete /var/metacat/data/ /mnt/pdg/repos/arctic/metacat/data/
                
                real    14286m43.628s
                user    1131m15.740s
                sys     3907m38.871s
                ## -> 9.92 days
                ```
              - subsequent repeat rsync
                ```shell
                brooke@arctica:~$ time sudo rsync -rltDHX  /var/metacat/data/ /mnt/pdg/repos/arctic/metacat/data/
                [sudo] password for brooke:
                
                real	4m19.047s
                user	0m15.747s
                sys	0m34.912s
                ```
              
### Persistent Volumes
- [x] Set up a PV to point to PROD cephfs `.../repos/arctic/metacat` for metacat
- [x] Set up a PV to point to PROD cephfs `.../repos/arctic/postgres` for postgres
- [x] Create a PVC for Postgresql; see `prod_cluster/metacatarctic/pvc--metacatarctic-postgres.yaml`
- [x] "csi-cephfs-sc-ephemeral" storageClass missing. Ask @nickatnceas to add, like he did for dev cluster:
```shell
  storageclass.storage.k8s.io "csi-cephfs-sc-ephemeral" not found
```

### MetacatUI setup
- [x] Copy config (tokens) from adc server

### Metacat Config
- [x] Add `values.yaml` overrides for non-default 2.19 settings (diff arcticdata.io `$TOMCAT_HOME/webapps/metacat/WEB-INF/metacat.properties` with default `metacat.properties` from 2.19 release)
- [x] Add `values.yaml` overrides for newly-introduced 3.0 settings (diff default `metacat.properties` from 3.0.0 release with default `metacat.properties` from 2.19 release)
- [x] Compare with test.arcticdata.io values overrides as a sanity check

### First Deployment 
- [x] Complete steps in ["First Install - IMPORTANT IF MOVING DATA FROM AN EXISTING LEGACY DEPLOYMENT"](https://github.nceas.ucsb.edu/NCEAS/k8s-cluster-config/blob/main/MetacatQuickRef.md) BEFORE first startup!

- [x] solr pods not starting. root cause from logs:
  ```shell
  $ kc logs pod/metacatarctic-solr-1
    /scripts/setup.sh: line 8: /opt/bitnami/scripts/solr/entrypoint.sh: Permission denied
  ```
  **SOLVED** - was overriding `extraVolumes` values, and the override didn't include the permissions line

- [x] `https://arctic-prod.test.dataone.org/catalog/` (trailing slash) works, but `https://arctic-prod.test.dataone.org/catalog` gives a 404 (nginx)
    - See https://github.com/kubernetes/ingress-nginx/issues/646
    - See https://stackoverflow.com/questions/71424259/why-url-re-writing-is-not-working-when-i-do-not-use-slash-at-the-end
      ```
        - path: /link1(/|$)
      ```
- [x] ensure all data and documents files are group writeable (otherwise, hashstore upgrader can't create hard links):
    ```shell
    sudo find /mnt/ceph/repos/arctic/metacat/data/ -type f ! -perm -g=w -exec chmod g+w {} +
    ```
- [x] `chown -R 59997:59997` the ceph dir corresponding to `/var/metacat`, and update values.yaml to use this uid:gid
    ```shell
    brooke@datateam:/mnt/ceph/repos/arctic$ time sudo chown -R 59997:59997 metacat

    real	4m7.026s
    user	0m0.004s
    sys	0m0.027s
    ```
- [x] Hostname aliases and rewrite rules
    - Figure out how to do these with ingress; see [all-sites-enabled.conf](https://github.nceas.ucsb.edu/NCEAS/k8s-cluster-config/blob/4bb7dc02274e44270889c328edf147c65fa27443/prod_cluster/metacatarctic/reference/all-sites-enabled.conf#L1). Lots of complexity - eg http://aoncadis.org aliased to adc.io, and site conf has RewriteMaps each having >3700 entries.
    - EXPLANATION: aoncadis.org was the predecessor to the ADC site. These rewrite rules map existing, old dataset urls to their new locations on ADC - so these rewrites need to be maintained somewhere
    - [x] Leave all the redirects/other sites on the current Apache host, and move only [arcticdata.io](http://arcticdata.io/).

### ATTENTION: Still To Do Before Final Deployment
- [x] Time hashstore conversion
- [x] Time reindex-all
- [x] MetacatUI + WordPress setup. How do we host it and link to k8s metacat?
    - [x] ACTION: use a wordpress image/bitnami chart, deployed separately from the metacat helm chart

- [x] ACTION: Ask @nickatnceas for help with letsencrypt certs - do we need to remove `arcticdata.io` from wildcard cert on arctica? NOTE: we still need subdomain certs there (ie status.adc, beta.adc).

- [x] Skip 3.0.0 and deploy 3.1.0, but only after it's been running on less-trafficked hosts for a while. See proposed release plan in Issue #1984.

**Comment by artntek** [comment]
update from Nick on rsync of /var/metacat/data:
> _after 16 hours we have 3.3 T copied… so looking like ~12 days until it’s finished_

**Comment by artntek** [comment]
Trying to resolve "permission denied" error on solr startup.
```shell
/scripts/setup.sh: line 8: /opt/bitnami/scripts/solr/entrypoint.sh: Permission denied
```

Can't test from within the solr pods, because they never start up - so instead created a (busybox) pod to do the same configmap mounts:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: metacatarctic-solr-config-mount-test
  namespace: arctic
spec:
  containers:
    - image: docker.io/busybox
      imagePullPolicy: IfNotPresent
      name: solr-config-mount
      command: [ "/bin/sh" ]
      args: [ "-c", "while true; do sleep 86400; done" ]
      volumeMounts:
        - name: scripts
          mountPath: /scripts/setup.sh
          subPath: setup.sh
        - mountPath: /solrconfig
          name: solr-config
        - mountPath: /opt/bitnami/scripts/solr/entrypoint.sh
          name: solr-config
          subPath: entrypoint.sh
  volumes:
    - name: scripts
      configMap:
        name: metacatarctic-solr-scripts
        defaultMode: 0755
    - configMap:
        name: metacatarctic-indexer-configfiles
        defaultMode: 0755
      name: solr-config
```

...and this shows that the entrypoint script is indeed non-executable:
```shell
$ ls -la /opt/bitnami/scripts/solr/entrypoint.sh
-rw-r--r--    1 root     root           780 Oct 14 22:37 /opt/bitnami/scripts/solr/entrypoint.sh
```

BUT - if I look at one of the solr pods on the existing test.adc.io instance, it's different:

```shell
 $ kcexec -it metacatarctic-solr-0 -- bash -c "ls -la /opt/bitnami/scripts/solr/entrypoint.sh"
-rwxrwxrwx 1 root 1001 780 Jul 29 19:44 /opt/bitnami/scripts/solr/entrypoint.sh
```

Using the same chart, why the difference between dev and prod clusters??
