### ISSUE TITLE
Chang the target-branch for dependabot

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1957]
The dependabot in Metacat currently runs against the main branch. 
We would like it to run against the develop branch. In the dataone-indexer project, there is a `dependabot.yml `file under the `.github` directory:

```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
        interval: "daily"
    target-branch: "develop"
```

We will use it in the main branch in Metacat.
