### ISSUE TITLE
Deploy ADC Wordpress as a bitnami chart

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1992]
In order to move arcticdata.io to k8s, we need a way of hosting the existing wordpress instance that serves the root of the https://arcticdata.io/ site.

This should be relatively straightforward by use of a bitnami chart.

Tasks:

- [x] Find suitable chart and test-deploy on dev cluster
  - `helm install wpbrooke bitnami/wordpress --version 24.0.7`
  - See [config options here](https://github.com/bitnami/charts/tree/main/bitnami/wordpress#wordpress-configuration-parameters)
  - Need to set at least:
   ```yaml
   global.defaultStorageClass: csi-cephfs-sc-ephemeral
                               # (for testing; csi-cephfs-sc for prod)
   wordpressUsername: 
   existingSecret: # (create a secret to contain wordpressPassword)
   ```
- [x] Determine how to export all settings and content from existing ADC wordpress instance, and import into k8s version
  - Use an existing database - [see docs](https://github.com/bitnami/charts/tree/main/bitnami/wordpress#external-database-support)
   ```yaml
   mariadb.enabled=false
   externalDatabase.host=myexternalhost
   externalDatabase.user=myuser
   externalDatabase.password=mypassword
   externalDatabase.database=mydatabase
   externalDatabase.port=3306
   # If the database already contains data from a previous WordPress 
   # installation, set:
   wordpressSkipInstall: true
   ```
- [x] customize ingress to serve wordpress in addition to adc site
