### ISSUE TITLE
nginx `proxy-set-headers` directive is namespace-specific

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#2022]
In order for DataONE replication to work, a k8s admin currently needs to add the nginx `proxy-set-headers` directive to the `ingress-nginx-controller` configMap (in the `ingress-nginx` namespace), as follows:

```yaml
data:
  allow-snippet-annotations: "true"
  proxy-set-headers: arctic/ingress-nginx-custom-headers
```

(This is typically achieved using a script - see [helm/admin/configure-nginx-mutual-auth.sh](https://github.com/NCEAS/metacat/blob/main/helm/admin/configure-nginx-mutual-auth.sh))

HOWEVER - that setting seems to be namespace-specific (see `arctic`, above). This won't work when we have more than one deployment in different namespaces sharing the same ingress.

* is the namespace necessary, or can we somehow apply in a "wildcard" fashion?
* or can the entry be repeated, once for each namespace?
* or??
