### ISSUE TITLE
Create a GitHub action for building docker images and storing them in GHCR

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#2058]
Create a GitHub action for building docker images and storing them in GHCR.

Initial thoughts on triggers:
- manual
- merges to `develop`?
- release tags

**Comment by mbjones** [comment]
Here's an example of this that I put together in 2022. The actions it uses are probably outdated and could be updated, but I think the approach still works fine.

**Comment by artntek** [comment]
here's an example of the one that's currently working for `dataone_indexer` 

https://github.com/DataONEorg/dataone-indexer/blob/main/.github/workflows/build-test-publish.yaml

The challenge is that it needs a maven build as input, but the metacat build still uses `ant`. Example Claude solution to build with ant (completely untested! Just FYI):

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build with Ant
        run: ant clean distbinmc  # your build target

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/  # path to your Ant build output
          retention-days: 1

## and add the corresponding download to 'docker-publish' job:
      # [...] 
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist/  # downloads into this path in the workspace
      # [...]
```
