### ISSUE TITLE
Set k8s container resources requests & limits for Metacat, and for PostgreSQL subchart

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#2100]
For k8s deployments of Metacat and PostgreSQL, we need to set realistic values the following, so they do not get `OOMKilled`:

```yaml
spec:
  containers:
    resources:
      requests:
        cpu: #value
        memory: #value
    limits:
      cpu: #value
      memory: #value
```

**Comment by artntek** [comment]
Also set for MetacatUI in the interim, since it doesn't set its own values
https://github.com/NCEAS/metacatui/issues/2640

**Comment by artntek** [comment]
Bitnami default allocation: ([see presets here](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L14))

```yaml
## PostgreSQL:
resourcesPreset: "nano"
## nano means:
## requests: cpu: 100m; memory: 128Mi 
## limits:   cpu: 150m; memory: 192Mi
```

**Comment by artntek** [comment]
## Default Chart Values

Proposed new presets (where available) or requests/limits (where not). These are the default values, so should be kept low in order to allow deployment on rancher desktop etc. They must be overridden for production deployments.

```yaml
## PostgreSQL:
resourcesPreset: "medium"
## medium means:
## requests: cpu: 500m; memory: 1024Mi 
## limits:   cpu: 750m; memory: 1536Mi

## Metacat:
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 2
    memory: 2Gi
```

## Suggested Production Values

```yaml
## PostgreSQL:
primary:
  resources:
    requests:
      cpu: 4
      memory: 32Gi
    limits:
      cpu: 4
      memory: 32Gi

## Metacat:
resources:
  requests:
    cpu: 12
    memory: 32Gi
  limits:
    cpu: 12
    memory: 32Gi
```
