### ISSUE TITLE
Bug: Large Bagit Archive Downloads Broken on Safari

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#2175]
## Steps to Reproduce
1. Log in as an admin and navigate to a big data package, like this one:
https://arcticdata.io/catalog/view/urn:uuid:ffd5761e-2f97-4840-acdd-e69f54d8e42e
2. (Open the network tab in the dev tools window)
2. Click the icon to download the entire package, which makes a request to this URL: `https://arcticdata.io/metacat/d1/mn/v2/packages/application%2Fbagit-1.0/resource_map_urn%3Auuid%3A7a79fe9d-99db-4829-a18f-b1bf498f0715`
3. The download eventually begins, and in the network tab, `Transfer Size` starts to increase

## Observed
After several minutes, the browser window reloads, and `Transfer Size` remins at somewhere between 350MB and 370MB

## Expected
Download should continue until the entire zipfile has been downloaded (4.2GB)

## Other Info
- The above steps work fine on Firefox and on Chrome.
- To make Chrome work, I added the following to the `ingress-nginx` config:
  ```yaml
    annotations:
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ## Can remove proxy-buffering after helm chart > 2.1.1
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      ## Not yet in metacat settings:
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/send-timeout: "3600"
      ## already in original metacat chart:
      #  nginx.ingress.kubernetes.io/client-body-buffer-size: "1m"
      #  nginx.ingress.kubernetes.io/client_max_body_size: "0"
      #  nginx.ingress.kubernetes.io/proxy-body-size: "0"
  ```

**Comment by artntek** [comment]
Here are the headers from each session:

## 1. SAFARI (FAILS)
```http
## GENERAL
URL: https://arcticdata.io/metacat/d1/mn/v2/packages/application%2Fbagit-1.0/resource_map_urn%3Auuid%3A7a79fe9d-99db-4829-a18f-b1bf498f0715
Status: 200
Source: Network
Initiator: PackageModel.js:1653

## REQUEST HEADERS
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9[...etc]
Referer: https://arcticdata.io/catalog/view/urn:uuid:ffd5761e-2f97-4840-acdd-e69f54d8e42e
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Safari/605.1.15

## RESPONSE HEADERS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS
Access-Control-Max-Age: 1728000
Content-Disposition: inline; filename="resource_map_urn_uuid_7a79fe9d_99db_4829_a18f_b1bf498f0715.zip"
Content-Type: application/zip
Date: Wed, 11 Jun 2025 15:26:29 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

## 2. FIREFOX (OK) 
```http
## GENERAL
GET https://arcticdata.io/metacat/d1/mn/v2/packages/application%2Fbagit-1.0/resource_map_urn%3Auuid%3A7a79fe9d-99db-4829-a18f-b1bf498f0715
Status: 200
Version: HTTP/2
Transferred: 4.20 GB (4.20 GB size)
Referrer: Policystrict-origin-when-cross-origin
Request: PriorityHighest
DNS: ResolutionSystem

## REQUEST HEADERS
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9[...etc]
Cookie: JSESSIONID=0581089D227E308FBE0F96AC56CC119D; _ga_12EKQM14SH=GS2.1[...etc]; _ga=GA1.1[...etc]
Priority: u=0
Referer: https://arcticdata.io/catalog/view/urn:uuid:ffd5761e-2f97-4840-acdd-e69f54d8e42e
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:139.0) Gecko/20100101 Firefox/139.0
Connection: keep-alive
Host: arcticdata.io
TE: trailers

## RESPONSE HEADERS
access-control-allow-credentials: true
access-control-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
access-control-allow-methods: POST, PUT, GET, OPTIONS
access-control-max-age: 1728000
content-disposition: inline; filename="resource_map_urn_uuid_7a79fe9d_99db_4829_a18f_b1bf498f0715.zip"
content-type: application/zip
date: Wed, 11 Jun 2025 16:04:21 GMT
strict-transport-security: max-age=31536000; includeSubDomains
X-Firefox-Spdy: h2
```

## 1. CHROME (OK)
```http
## GENERAL
URL: https://arcticdata.io/metacat/d1/mn/v2/packages/application%2Fbagit-1.0/resource_map_urn%3Auuid%3A7a79fe9d-99db-4829-a18f-b1bf498f0715
Request_Method: GET
Status_Code: 200 OK
Remote_Address: 128.111.85.192:443
Referrer_Policy: strict-origin-when-cross-origin

## REQUEST HEADERS
accept: */*
accept-encoding: gzip, deflate, br, zstd
accept-language: en-US,en;q=0.9
authorization: Bearer eyJhbGciOiJSUzI1NiJ9[...etc]
cookie: JSESSIONID=D7EBDED390A7EDCCAE8C6D7B7670F33D; _ga=GA1.1.[...etc]; wp-settings-time-32=1746659592; _ga_12EKQM14SH=GS2.1.[...etc]
priority: u=1, i
referer: https://arcticdata.io/catalog/view/urn:uuid:ffd5761e-2f97-4840-acdd-e69f54d8e42e
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
authority: arcticdata.io
cache-control: no-cache
method: GET
path: /metacat/d1/mn/v2/packages/application%2Fbagit-1.0/resource_map_urn%3Auuid%3A7a79fe9d-99db-4829-a18f-b1bf498f0715
scheme: https
sec-ch-ua: "Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
dnt: 1
pragma: no-cache

## RESPONSE HEADERS
access-control-allow-credentials: true
access-control-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
access-control-allow-methods: POST, PUT, GET, OPTIONS
access-control-max-age: 1728000
content-disposition: inline; filename="resource_map_urn_uuid_7a79fe9d_99db_4829_a18f_b1bf498f0715.zip"
content-type: application/zip
date: Tue, 10 Jun 2025 23:12:06 GMT
strict-transport-security: max-age=31536000; includeSubDomains
```

**Comment by taojing2002** [comment]
@mbjones @robyngit @jeanetteclark @artntek The methods of `v1/v2 mn/cn.getObject` use the same `inline` keyword in the respond's header. I am going to change it to `download` as well. Do you have any concerns about the change?

**Comment by artntek** [comment]
Jing changed the `Content-Disposition` header from `inline` to `download`. However, we still see the same issue with Safari:
- Testing on k8s (ingress-nginx), the download still fails (and the page refreshes) around 350MB (of 4.2GB)
- Testing on dev.nceas.ucsb.edu (legacy deployment w/ Apache, and still using `Content-Disposition: inline`), the download fails (and the page refreshes) around 1.23GB (of 4.2GB)

**Comment by artntek** [comment]
Setting these did not change anything:

```yaml
## values.yaml
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"  # Disable temp file limit
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"      # Increase body size, even for downloads

## ingress-nginx configmap
  data:
    proxy_connect_timeout 600s;
```

Tried forcing HTTP v1 between nginx and metacat (chatgpt suggestion) but no benefit there

I'm reading in various places that Safari is bad at dealing with streaming `chunked` responses where the content size is unknown. The only thing we haven't tried is setting the `Content-Length` header, but this is not possible when using speed-bagit, that zips and streams in realtime. If we wanted to do this, we'd need to first create the zip and save to disk so we could calculate its size, which is not great
